# title: Amber Labs Devops Assessment
# remote_theme: pages-themes/cayman@v0.2.0
# plugins:
# - jekyll-remote-theme
title: Devops Assessment
description: Amber Labs, 2024
# show_downloads: true
google_analytics:
theme: jekyll-theme-midnight
